### PR TITLE
Show all errors/ warning messages

### PR DESCRIPTION
**Pull request by aq17**
Addresses #254

### CODE REVIEW

**Comment by aq17** [comment]
Example output:
```
error: failed to discover plugin requirements: 
-error: Pulumi.yaml:13,7-41: missing function name ('Function'); missing function name ('Function')
-warning: Pulumi.yaml:8,5-13: Field 'required' does not exist on Object 'configuration.name'; Existing fields are: 'secret', 'type', 'default'
```

**Comment by AaronFriel** [comment]
@aq17 the extended output looks good, is it easy to remove the duplication on the error though?

```
-error: Pulumi.yaml:13,7-41: missing function name ('Function'); missing function name ('Function')
```

**Comment by AaronFriel** [comment]
I think tests are failing due to #280, which might be due to merging a PR that bumped codegen from pulumi/pulumi without updating tests. Once #281 is merged, I expect the test failures to disappear.

**Comment by aq17** [comment]
> @aq17 the extended output looks good, is it easy to remove the duplication on the error though?
> 
> ```
> -error: Pulumi.yaml:13,7-41: missing function name ('Function'); missing function name ('Function')
> ```

The `hcl` pkg we import from Hashicorp prints error/ warning messages with this format `return fmt.Sprintf("%s: %s; %s", d.Subject, d.Summary, d.Detail)`; right now we set Detail as Summary if there are no additional details, so we could omit but it'd still have the semicolon

```
error: failed to discover plugin requirements: 
-error: Pulumi.yaml:13,7-41: missing function name ('Function'); 
-warning: Pulumi.yaml:8,5-13: Field 'required' does not exist on Object 'configuration.name'; Existing fields are: 'secret', 'type', 'default'
```
Does that work?

**Comment by AaronFriel** [comment]
Yeah, I think that looks better to me - let's omit the duplication there.

**Comment by AaronFriel** [comment]
@iwahbe curious if you agree here on removing the "detail" if it's duplicative. I think it makes sense?

**Comment by iwahbe** [comment]
I'm happy to remove the duplicative detail.

**Review by AaronFriel — APPROVED** [review]

**Review by AaronFriel — CHANGES_REQUESTED** [review]
Tests need to be updated with the changed error reporting:

https://github.com/pulumi/pulumi-yaml/runs/7311777561?check_suite_focus=true#step:13:770

**Pull request merged**
