### PR TITLE
Changelog for v1.11.0

### PR DESCRIPTION
**Pull request by tgummerer**
I missed a step in https://github.com/pulumi/pulumi-yaml/pull/658 :grimacing:

### CODE REVIEW

**Review by justinvp — APPROVED** [review]

**Comment by nafg** [comment]
The links are for pulumi-dotnet

**Comment by justinvp** [comment]
Yes, the links should be fixed in main. https://github.com/pulumi/pulumi-yaml/pull/663/commits/59ec4ddacda754e0ae5cefdc6b3be7016cd57b35

**Comment by nafg** [comment]
Ah. But they aren't fixed in the GitHub release notes at https://github.com/pulumi/pulumi-yaml/releases/tag/v1.11.0

**Comment by tgummerer** [comment]
Thanks for noticing that!  I've fixed them up manually there now.

**Pull request merged**
