### PR TITLE
ci: Upgrade to latest golangci-lint

### PR DESCRIPTION
**Pull request by abhinav**
Upgrades to the latest release of golangci-lint.
This will allow enabling more checks, using the GitHub action, etc.

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* main
  * **PR #470** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/470" target="_blank">Graphite</a> 
    * **PR #471** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/471" target="_blank">Graphite</a> 
      * **PR #473** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/473" target="_blank">Graphite</a>  👈
        * **PR #472** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/472" target="_blank">Graphite</a> 
    * **PR #469** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/469" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/473?utm_source=stack-comment).

**Review by dixler — APPROVED** [review]

**Comment by abhinav** [comment]
@abhinav started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/473).

**Comment by abhinav** [comment]
[Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/473) rebased this pull request as part of a merge.

**Comment by abhinav** [comment]
@abhinav merged this pull request with [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-yaml/473).

**Pull request merged**
